### ISSUE TITLE
visiting Next Docs we get Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by MINORITYmaN** [vuetifyjs/docs-next#150]
Windows 10 Pro 64 bit 1909
MS Edge 84.0.522.61 64 bit stable
Google Chrome 84.0.4147.135 64 bit stable

![image](https://user-images.githubusercontent.com/2734697/90762296-17a07000-e2e5-11ea-9ea8-dce9ca54b58e.png)

ok let's do so

`Uncaught SyntaxError: Unexpected token '<'`

![image](https://user-images.githubusercontent.com/2734697/90762083-b2e51580-e2e4-11ea-92b7-395aec343fea.png)

**Comment by Mert75** [comment]
we are aware of this issue, new docs are still under development though
