### ISSUE TITLE
Page is not responsive.

### ISSUE THREAD

**Issue by benyou1969** [vuetifyjs/docs-next#27]
the page is not showing content correctly, I had to zoom out to -70%

![image](https://user-images.githubusercontent.com/31636863/85291662-ac782000-b492-11ea-9d11-56aafb6bfaae.png)

not responsive for screen width: under `1900px`.
[next.vuetifyjs.com](https://next.vuetifyjs.com/en/)

**Comment by MajesticPotatoe** [comment]
This has been resolved
